added signicat authorization scheme
privacybydesign/irma-demo-schememanager pull request #111
Opened 2023-07-05 09:17 UTC by michielmayer

2023-07-05 09:51 UTC, sanderhollaar requested changes

2023-07-05 09:51 UTC, sanderhollaar commented on signicat/Issues/authorization/description.xml
> +				<nl>Peilmoment is het moment dat de gegevens uit het handelsregister zijn onttrokken (formaat jjjjmmddhhmmssmmm)</nl>
s/ontrokken/opgevraagd/

2023-07-05 09:51 UTC, sanderhollaar commented on signicat/Issues/authorization/description.xml
> +				<nl>Peilmoment (opvraagmoment uit handelsregister)</nl>
~~(opvraagmoment uit handelsregister)~~

2023-07-05 09:51 UTC, sanderhollaar commented on signicat/Issues/authorization/description.xml
> +		<nl>Machtiging voor een organisatie, uitgegeven door een functionaris die geregistreerd staat in het KVK handelsregister.</nl>
maybe remove the trailing dots to match the other Description fields

2023-07-05 09:51 UTC, sanderhollaar commented on signicat/Issues/authorization/description.xml
> +				<en>Address of the organisation</en>
~~of the organisation~~

2023-07-05 09:51 UTC, sanderhollaar commented on signicat/Issues/authorization/description.xml
> +				<nl>Adres van de organisatie</nl>
~~van de organisatie~~

2023-07-05 14:35 UTC, michielmayer commented
In the last commit, I changed the order of the attributes. We decided It is better to have the company and the authorization on top, so the user does not have to scroll in the app to decide if he shares the correct credential.

2023-07-11 11:39 UTC, sanderhollaar submitted a review, later dismissed

2023-07-11 11:42 UTC, sanderhollaar approved these changes

2023-07-11 11:43 UTC, bobhageman approved these changes

2023-07-11 11:44 UTC, ivard approved these changes

2023-07-11 11:50 UTC, merged