textual corrections and a new demo
privacybydesign/irma-demo-schememanager pull request #122
Opened 2023-11-21 08:44 UTC by jpvdplasse

2023-11-21 13:52 UTC, bobhageman commented on VeriD/Issues/postnl/description.xml
> +				<nl>Voorkeuren van bezorgen: adres, pakketpunt , parcel locker</nl>
Missed one where there is a superfluous space after `pakketpunt`

2023-11-21 15:27 UTC, bobhageman approved these changes

2023-11-21 15:52 UTC, sanderhollaar requested changes

2023-11-21 15:52 UTC, sanderhollaar commented on VeriD/Issues/postnl/description.xml
> +				<nl>Voorkeuren van bezorgen: adres, pakketpunt, parcel locker</nl>
Voorkeur~en~

2023-11-21 15:52 UTC, sanderhollaar commented on VeriD/Issues/postnl/description.xml
> +				<nl>Niet thuis voorkeur: naar buren of naar pakketpunt, afgesproken plek.</nl>
Not-at-home
Niet-thuis
`s/ of/,/`

2023-11-21 15:52 UTC, sanderhollaar commented on VeriD/Issues/postnl/description.xml
> +				<en>Not at home preference</en>
Not -at-home preference

2023-11-21 15:52 UTC, sanderhollaar commented on VeriD/Issues/postnl/description.xml
> +				<nl>Niet thuis voorkeur</nl>
Niet-thuis voorkeur

2023-11-21 15:52 UTC, sanderhollaar commented on VeriD/Issues/seizures/description.xml
> +				<nl>Beslag gelegd op bankrekening</nl>
Beslaggelegd

2023-11-21 15:52 UTC, sanderhollaar commented on VeriD/Issues/seizures/description.xml
>  				<nl>Beslag gelegd op uitkering</nl>
Beslaggelegd

2023-11-21 15:52 UTC, sanderhollaar commented on VeriD/Issues/seizures/description.xml
>  				<nl>Beslag gelegd op inkomen</nl>
Beslaggelegd

2023-11-22 08:09 UTC, sanderhollaar approved these changes

2023-11-22 08:14 UTC, bobhageman approved these changes

2023-11-22 08:14 UTC, merged