demo green card
privacybydesign/irma-demo-schememanager pull request #133
Opened 2024-08-09 16:39 UTC by jpvdplasse

2024-08-13 10:41 UTC, MartijnYivi submitted a review, later dismissed

2024-08-13 11:57 UTC, ivard requested changes
Looks good. I only found a minor spelling issue.

2024-08-13 11:57 UTC, ivard commented on VeriD/Issues/imic/description.xml
> +		<Attribute id="vehicleRegistrationnNumber">
There is `n` to much in `Registrationn`

2024-08-13 12:12 UTC, jpvdplasse commented on VeriD/Issues/imic/description.xml
> +		<Attribute id="vehicleRegistrationnNumber">
thank you, fixed

2024-08-13 12:58 UTC, MartijnYivi approved these changes

2024-08-14 08:05 UTC, ivard approved these changes

2024-08-14 08:06 UTC, merged